#!/bin/bash
# Used to output the battery level when working in a fullscreen Tmux
# environment.

if [ `uname` = 'Darwin' ] ; then
  percent=`pmset -g batt | grep -Eo "\d+%" | cut -d% -f1`
fi

if   (( percent > 20 )); then color='#[fg=default none]'
elif (( percent > 10 )); then color='#[fg=colour3 bold]'
                         else color='#[fg=colour1 bold]'
fi
echo "$color$percent%"
